### ISSUE TITLE
Getting undefined local variable or method when using `ohai` cookbook with chef 14

### ISSUE THREAD

**Issue by snehitgajjar** [chef-cookbooks/ohai#71]
### Cookbook version
`5.2`

### Chef-client version
```
provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  install_strategy: always
  deprecation_as_error: true
  client_rb:
    Ohai::Config[:directory] =: '/etc/chef/ohai_plugins'
```

### Platform Details
`rhel69`

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:
Add `ohai-5.2` into `metadata.rb` as a denepdency. Then use `ohai_plugin '<plugin_name>'` resource which will throw this error.

### Expected Result:
It should converge successfully by creating `ohai_plugin`

### Actual Result:
https://gist.github.com/snehitgajjar/6c47fe3efb552ce9244f2aae87271ea0

**Comment by snehitgajjar** [comment]
Closing as it was an issue `4.2.3`. It works fine with `5.2.x`
